import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import workersRouter from "./workers.js";
import aiRouter from "./ai.js";
import authRouter from "./auth.js";
import hoursRouter from "./hours.js";
import payrollRouter from "./payroll.js";
import documentsRouter from "./documents.js";
import adminsRouter from "./admins.js";
import historyRouter from "./history.js";
import logsRouter from "./logs.js";
import settingsRouter from "./settings.js";
import siteCoordinatorsRouter from "./site-coordinators.js";
import tenantsRouter from "./tenants.js";
import gdprRouter from "./gdpr.js";
import faceAuthRouter from "./face-auth.js";
import documentWorkflowRouter from "./document-workflow.js";
import contractsRouter from "./contracts.js";
import signaturesRouter from "./signatures.js";
import postedWorkersRouter from "./posted-workers.js";
import countryComplianceRouter from "./country-compliance.js";
import gpsRouter from "./gps.js";
import pushRouter from "./push.js";
import analyticsRouter from "./analytics.js";
import platformRouter from "./platform.js";
import filesRouter from "./files.js";
import regulatoryRouter from "./regulatory.js";
import trcServiceRouter from "./trc-service.js";
import availabilityRouter from "./availability.js";
import shiftsRouter from "./shifts.js";
import skillsRouter from "./skills.js";
import aiAuditRouter from "./ai-audit.js";
import billingRouter from "./billing.js";
import clientsRouter from "./clients.js";
import jobsRouter from "./jobs.js";
import invoicesRouter from "./invoices.js";
import applicationsRouter from "./applications.js";
import immigrationRouter from "./immigration.js";
import onboardingRouter from "./onboarding.js";
import crmRouter from "./crm.js";
import zusRouter from "./zus.js";
import matchingRouter from "./matching.js";
import moodRouter from "./mood.js";
import voiceRouter from "./voice.js";
import advancesRouter from "./advances.js";
import certifiedSignaturesRouter from "./certified-signatures.js";
import benchRouter from "./bench.js";
import googleRouter from "./google.js";
import contractGenRouter from "./contract-gen.js";
import selfServiceRouter from "./self-service.js";
import roiRouter from "./roi.js";
import finesRouter from "./fines.js";
import trustRouter from "./trust.js";
import churnRouter from "./churn.js";
import housingRouter from "./housing.js";
import revenueRouter from "./revenue.js";
import salaryRouter from "./salary.js";
import legalRouter from "./legal.js";
import safetyRouter from "./safety.js";
import competitorsRouter from "./competitors.js";
import countryConfigRouter from "./country-config.js";
import fraudRouter from "./fraud.js";
import translateRouter from "./translate.js";
import messagingRouter from "./messaging.js";
import insuranceRouter from "./insurance.js";
import skillsGapRouter from "./skills-gap.js";
import careersRouter from "./careers.js";
import marginsRouter from "./margins.js";
import geoRouter from "./geo.js";
import signalsRouter from "./signals.js";
import identityRouter from "./identity.js";
import guaranteesRouter from "./guarantees.js";
import whitelabelRouter from "./whitelabel.js";
import frameworksRouter from "./frameworks.js";
import legalKbRouter from "./legal-kb.js";
import saasBillingRouter from "./saas-billing.js";
import postedNotificationsRouter from "./posted-notifications.js";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(workersRouter);
router.use(hoursRouter);
router.use(payrollRouter);
router.use(documentsRouter);
router.use(adminsRouter);
router.use(historyRouter);
router.use(logsRouter);
router.use(settingsRouter);
router.use(siteCoordinatorsRouter);
router.use(gdprRouter);
router.use(faceAuthRouter);
router.use(documentWorkflowRouter);
router.use(contractsRouter);
router.use(signaturesRouter);
router.use(postedWorkersRouter);
router.use(countryComplianceRouter);
router.use(gpsRouter);
router.use(pushRouter);
router.use(analyticsRouter);
router.use(platformRouter);
router.use(filesRouter);
router.use(aiRouter);
router.use(regulatoryRouter);
router.use(trcServiceRouter);
router.use(availabilityRouter);
router.use(shiftsRouter);
router.use(skillsRouter);
router.use(aiAuditRouter);
router.use(billingRouter);
router.use(clientsRouter);
router.use(jobsRouter);
router.use(invoicesRouter);
router.use(applicationsRouter);
router.use(immigrationRouter);
router.use(onboardingRouter);
router.use(crmRouter);
router.use(zusRouter);
router.use(matchingRouter);
router.use(moodRouter);
router.use(voiceRouter);
router.use(advancesRouter);
router.use(certifiedSignaturesRouter);
router.use(benchRouter);
router.use(googleRouter);
router.use(contractGenRouter);
router.use(selfServiceRouter);
router.use(roiRouter);
router.use(finesRouter);
router.use(trustRouter);
router.use(churnRouter);
router.use(housingRouter);
router.use(revenueRouter);
router.use(salaryRouter);
router.use(legalRouter);
router.use(safetyRouter);
router.use(competitorsRouter);
router.use(countryConfigRouter);
router.use(fraudRouter);
router.use(translateRouter);
router.use(messagingRouter);
router.use(insuranceRouter);
router.use(skillsGapRouter);
router.use(careersRouter);
router.use(marginsRouter);
router.use(geoRouter);
router.use(signalsRouter);
router.use(identityRouter);
router.use(guaranteesRouter);
router.use(whitelabelRouter);
router.use(frameworksRouter);
router.use(legalKbRouter);
router.use(saasBillingRouter);
router.use(postedNotificationsRouter);

export default router;
