import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import workersRouter from "./workers.js";
import aiRouter from "./ai.js";
import authRouter from "./auth.js";
import hoursRouter from "./hours.js";
import payrollRouter from "./payroll.js";
import documentsRouter from "./documents.js";
import adminsRouter from "./admins.js";
import historyRouter from "./history.js";
import logsRouter from "./logs.js";
import settingsRouter from "./settings.js";
import siteCoordinatorsRouter from "./site-coordinators.js";
import tenantsRouter from "./tenants.js";
import gdprRouter from "./gdpr.js";
import faceAuthRouter from "./face-auth.js";
import documentWorkflowRouter from "./document-workflow.js";
import contractsRouter from "./contracts.js";
import signaturesRouter from "./signatures.js";
import postedWorkersRouter from "./posted-workers.js";
import countryComplianceRouter from "./country-compliance.js";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(workersRouter);
router.use(hoursRouter);
router.use(payrollRouter);
router.use(documentsRouter);
router.use(adminsRouter);
router.use(historyRouter);
router.use(logsRouter);
router.use(settingsRouter);
router.use(siteCoordinatorsRouter);
router.use(gdprRouter);
router.use(faceAuthRouter);
router.use(documentWorkflowRouter);
router.use(contractsRouter);
router.use(signaturesRouter);
router.use(postedWorkersRouter);
router.use(countryComplianceRouter);
router.use(aiRouter);

export default router;
